# Proyecto de Investigación - Cambios temporales en la carga hospitalaria

## Integrantes
- Sebastián Herrera Sarmiento
- Benjamín Bravo Albornoz

In [18]:
# Preparación entorno

import pandas as pd
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('dataset_rem2026.csv', sep=';')
display(dataset.head())
dataset.describe()
dataset_periodo = dataset.groupby('PERIODO').agg({'INDICE_OCUPACIONAL': 'mean', 'LETALIDAD': 'mean'}).reset_index()
display(dataset_periodo)

,PERIODO,TIPO_PERTENENCIA,COD_SSS,GLOSA_SSS,CODIGO_ESTABLECIMIENTO,ESTABLECIMIENTO,COD_AREA_FUNCIONAL,AREA_FUNCIONAL,MES,DIAS_CAMAS_OCUPADAS,DIAS_CAMAS_DISPONIBLES,DIAS_ESTADA,NUMERO_EGRESOS,EGRESOS_FALLECIDOS,TRASLADOS,INDICE_OCUPACIONAL,PROMEDIO_CAMAS_DISPONIBLE,PROMEDIO_DIAS_ESTADA,LETALIDAD,INDICE_ROTACION
0,2014,1,1,Arica,101100,Hospital Dr Juan Noé Crevanni (Arica),405,Área Cuidados Intensivos Adultos,1,139,186,115,9,7,12,74.73,6.0,12.78,77.78,1.50
1,2014,1,1,Arica,101100,Hospital Dr Juan Noé Crevanni (Arica),405,Área Cuidados Intensivos Adultos,2,103,168,164,7,4,21,61.31,6.0,23.43,57.14,1.17
2,2014,1,1,Arica,101100,Hospital Dr Juan Noé Crevanni (Arica),405,Área Cuidados Intensivos Adultos,3,117,186,98,15,9,12,62.90,6.0,6.53,60.00,2.50
3,2014,1,1,Arica,101100,Hospital Dr Juan Noé Crevanni (Arica),405,Área Cuidados Intensivos Adultos,4,126,180,114,7,5,17,70.00,6.0,16.29,71.43,1.17
4,2014,1,1,Arica,101100,Hospital Dr Juan Noé Crevanni (Arica),405,Área Cuidados Intensivos Adultos,5,141,186,165,11,7,19,75.81,6.0,15.00,63.64,1.83

    PERIODO  INDICE_OCUPACIONAL  LETALIDAD
0      2014           64.421340   7.623138
1      2015           64.846314   7.643165
2      2016           63.690429   7.755809
3      2017           63.744643   7.854660
4      2018           65.776845   7.782684
5      2019           66.077504   7.850920
6      2020           54.896112   8.020641
7      2021           59.433790   7.908988
8      2022           64.030589   7.765899
9      2023           66.882792   7.585210
10     2024           66.742295   7.489446
11     2025           67.538762   7.526477